### ISSUE TITLE
press F10 no response

### ISSUE THREAD

**Issue by bolin12** [archibate/vimrc#15]
I want to open NERDTree by  F10 ,but no response

**Comment by archibate** [comment]
try :NERDTreeToggle











无法顺畅的大口呼吸，是活着的最好证明

---Original---
From: ***@***.***&gt;
Date: Sat, Sep 17, 2022 12:02 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [archibate/vimrc] press F10 no response (Issue #15)




 
I want to open NERDTree by  F10 ,but no response

**Comment by archibate** [comment]
What terminal are you using, gnome? macos? if :NERDTreeToggle work but F10 not work, this could be your terminal have a hotkey conflict in F10.









无法顺畅的大口呼吸，是活着的最好证明

---Original---
From: ***@***.***&gt;
Date: Sat, Sep 17, 2022 12:02 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [archibate/vimrc] press F10 no response (Issue #15)




 
I want to open NERDTree by  F10 ,but no response
