### ISSUE TITLE
latest release error `tail: cannot open`

### ISSUE THREAD

**Issue by RodenLuo** [archibate/vimrc#17]
After downloading [vimrc-install.sh](https://github.com/archibate/vimrc/releases/download/v0.5/vimrc-install.sh)
```bash
$ bash vimrc-install.sh 
tail: cannot open 'vimrc-install.sh' for reading: No such file or directory

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

Ubuntu 20.04

---
`curl -sLf http://142857.red/vimrc-install.sh | bash` works fine.

**Comment by archibate** [comment]
Sorry, forgot to sync GitHub release with `142857.red`, fixed now.
