### ISSUE TITLE
Macos 不管是修改了airline配置 还是根据下面链接配置了lightline-bufferline 打开多个文件 都不能在顶部显示buffer标签

### ISSUE THREAD

**Issue by zhuting233** [archibate/vimrc#19]
根据此链接配置的ightline-bufferline： https://zhuanlan.zhihu.com/p/538746711

<img width="890" alt="image" src="https://user-images.githubusercontent.com/45703790/196027518-f28dcd11-9b46-418f-9e5b-3af7cfb36cf5.png">

**Comment by zhuting233** [comment]
在lightline-bufferline下面找到了解决办法
Q: I can't see the tabline!
A: Add set showtabline=2 to your configuration. This forces the tabline to always show.

但是鼠标点击标签栏不能切换标签，只能创建新文件

**Comment by archibate** [comment]
我也没有那个tabline，我是用,b快速切换不同buffer的，f2和f3快捷键可以切换到前后两个buffer











无法顺畅的大口呼吸，是活着的最好证明

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月16日(周日) 晚上7:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [archibate/vimrc] Macos 不管是修改了airline配置 还是根据下面链接配置了lightline-bufferline 打开多个文件 都不能在顶部显示buffer标签 (Issue #19)




 
在lightline-bufferline下面找到了解决办法
 Q: I can't see the tabline!
 A: Add set showtabline=2 to your configuration. This forces the tabline to always show.
 
但是鼠标点击标签栏不能切换标签，只能创建新文件
