### ISSUE TITLE
Arch linux - branch nvim-2  install error

### ISSUE THREAD

**Issue by zydza** [archibate/vimrc#23]
系统：Arch Linux (virtualbox虚拟机)
问题1 ：在运行`curl -sLf http://142857.red/nvimrc-install.sh | bash`之后，出现如下输出：
```
-- Checking NeoVim version...
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
-- NeoVim 0.9.1 or above not found, installing latest for you
main: line 272988: /usr/bin/nvim: Permission denied
x=$$; mkdir -p /tmp/_nvim_appimg_.$x && bash -c "cd /tmp/_nvim_appimg_.$x && /usr/bin/.nvim.appimage.noextract --appimage-extract > /dev/null 2>&1" && /tmp/_nvim_appimg_.$x/squashfs-root/AppRun "$@"; x=$?; rm -rf /tmp/_nvim_appimg_.$x exit $x
bash: line 272992: /usr/bin/nvim: Permission denied

```
问题2 ：在我已经安装neovim且版本为0.9.1的情况下，运行安装文件时，仍然会显示`-- NeoVim 0.9.1 or above not found, installing latest for you`

**Comment by zlqferris** [comment]
把http://142857.red/nvimrc-install.sh 下载下来, 修改下面两行就可以了
......
272980行 `$SUDO chmod u+x /usr/bin/nvim` 改为 `$SUDO chmod +x /usr/bin/nvim`
......
272985行 `$SUDO chmod u+x ./nvim.appimage` 改为 `$SUDO chmod +x ./nvim.appimage`

**Comment by zydza** [comment]
> 把http://142857.red/nvimrc-install.sh 下载下来, 修改下面两行就可以了 ...... 272980行 `$SUDO chmod u+x /usr/bin/nvim` 改为 `$SUDO chmod +x /usr/bin/nvim` ...... 272985行 `$SUDO chmod u+x ./nvim.appimage` 改为 `$SUDO chmod +x ./nvim.appimage`

十分感谢！实测修改后就成功了
