### ISSUE TITLE
如何清除Mason安装失败的信息

### ISSUE THREAD

**Issue by Akiramex** [archibate/vimrc#28]
![Snipaste_2024-06-05_11-24-12](https://github.com/archibate/vimrc/assets/78923489/57cf8fd5-33d7-467b-bd60-22331fb2f3d5)
每次打开nvim都会弹出这几个，怎么安装或者取消安装或者清除失败信息？

**Comment by archibate** [comment]
编辑 `~/.config/nvim/lua/archvim/config/mason.lua`：

```lua
require("mason-lspconfig").setup {
    ensure_installed = { "clangd", "cmake", "pyright", "lua_ls", "tsserver" },
    automatic_installation = true,
}
```

改为

```lua
require("mason-lspconfig").setup {
    ensure_installed = { "clangd", "cmake", "lua_ls", "tsserver" },
    automatic_installation = true,
}
```

即可不自动安装 pyright。

另外，能否让我看一下 `:MasonLog`？可能是你的系统没有 python3 导致安装失败。

**Comment by Akiramex** [comment]
感谢回答，确实是没有python3。另外有没有计划出一期使用指南，nvim新手用着一脸懵
