### ISSUE TITLE
【macOS】安装过程遇到问题

### ISSUE THREAD

**Issue by hyv5** [archibate/vimrc#35]
0. 系统信息: macOS 14.6.1 (Apple M2)
1. 事前通过brew install neovim的方式安装过neovim, 但本次安装前删除了～/.config/nvim
```shell
% nvim -V1 -v
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/opt/homebrew/Cellar/neovim/0.10.1/share/nvim"

```
2. 通过curl -sSLf https://142857.red/files/nvimrc-install.sh | bash 在线安装有以下报错信息
```
-- Welcome to the ArchVim installation script
FreeBSD base64
-- Fetching bundled data...
-- 正在下载插件包，请稍等...
-- Extracting bundled data...
-- Checking NeoVim version...
16777239 1545566 lrwxr-xr-x 1 yuanhe admin 0 32 "Sep 16 13:19:48 2024" "Sep 16 13:19:48 2024" "Sep 16 13:19:48 2024" "Sep 16 13:19:48 2024" 4096 0 0 /opt/homebrew/bin/nvim
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128
Run "nvim -V1 -v" for more info
-- NeoVim 0.9.1 or above not found, installing latest for you
cp: /usr/bin/nvim: Operation not permitted
```

补充信息:
1. 给在线安装命令加sudo没有效果
2. 使用brew uninstall neovim后再执行安装命令， 有以下报错信息：
```
% brew uninstall neovim
Uninstalling /opt/homebrew/Cellar/neovim/0.10.1... (1,897 files, 29.8MB)
(省略部分log)
% nvim
zsh: command not found: nvim
% curl -sSLf https://142857.red/files/nvimrc-install.sh | bash 
-- Welcome to the ArchVim installation script
FreeBSD base64
-- Fetching bundled data...
-- 正在下载插件包，请稍等...
-- Extracting bundled data...
-- Checking NeoVim version...
stat: : stat: No such file or directory
Password:
chmod: : No such file or directory
bash: line 527238: nvim: command not found
bash: line 527239: nvim: command not found
-- NeoVim 0.9.1 or above not found, installing latest for you
cp: /usr/bin/nvim: Operation not permitted
```
我的stat命令是好用的

**Comment by archibate** [comment]
对不起！我好像没有处理nvim没安装的情况，我重新上传了修复后的脚本，现在试试看还可以吗？

**Comment by hyv5** [comment]
感谢小彭老师

经过测试，有以下报错信息
```
% curl -sSLf https://142857.red/files/nvimrc-install.sh | bash
-- Welcome to the ArchVim installation script
-- 欢迎使用小彭老师 ArchVim 一键安装脚本
-- Fetching bundled data...
-- 正在下载插件包，请稍等...
-- Extracting bundled data...
-- Checking NeoVim version...
-- NeoVim 0.9.1 or above not found, installing latest for you
Password:
cp: /usr/bin/nvim: Operation not permitted
```

查找[资料](https://stackoverflow.com/questions/32659348/operation-not-permitted-when-on-root-el-capitan-rootless-disabled)后发现macOS系统对/usr/bin目录有SIP保护， 我手动将nvimrc-install.sh中的/usr/bin全部替换为/usr/local/bin后测试OK

**Comment by hyv5** [comment]
另外发现如果是macos的话似乎还需要在install_nvim()函数中下载nvim.appimage时选取对应的版本。。

**Comment by archibate** [comment]
我尝试修复了一下，
```bash
    elif [ \"x\$(uname -s)\" = \"xDarwin\" ]; then
        brew uninstall neovim 2> /dev/null || true
        brew install neovim
```
不知道brew是否能安装到最新版本？以及自动运行`:TSInstall cpp`：
```bash
fi
echo '-- Verifying treesitters...'
nvim --headless -c \"TSInstallInfo\" -c 'sleep 1 | q!' 2>&1 | grep -v 'not installed' || echo 'no installed treesitters?'
if [ \"x\$(uname -sm)\" != \"xLinux x86_64\" ]; then
    for x in ${treesitters[*]}; do
        nvim --headless -c \"TSUpdateSync \$x\" -c 'sleep 1 | q!'
    done
    nvim --headless -c \"TSInstallInfo\" -c 'sleep 1 | q!'
fi
```
你可以试试看。

**Comment by hyv5** [comment]
感谢小彭老师

经过测试安装流程可以走完，不过好像安装过程有些意外情况:
1. brew提示不能在root权限下使用， 而我是用普通权限运行的命令
2. 安装脚本在提示输入[y/n]时没有等待输入，而是继续执行并有错误报出

以上详见安装日志:
[install_log.txt](https://github.com/user-attachments/files/17043137/install_log.txt)

**Comment by hyv5** [comment]
补充：
以上情况2种没有等待输入的问题可能是brew没有正确安装依赖， 以普通权限运行bash ~/.config/nvim/install_deps.sh后再运行安装脚本就好了， 不过还是会有错误报出， 错误与前述日志一致， 即：
```
处理 /Users/yuanhe/.config/nvim/lua/archvim/predownload/Civitasv/cmake-tools.nvim/plugin/cmake-tools.lua 时发生错误:
E5113: Error while calling lua chunk: ...ownload/Civitasv/cmake-tools.nvim/plugin/cmake-tools.lua:4: loop or previous error loading module 'cmake-tools'
stack traceback:
	[C]: in function 'require'
	...ownload/Civitasv/cmake-tools.nvim/plugin/cmake-tools.lua:4: in main chunk
处理 command line 时发生错误:
packer.nvim: Error running config for cmake-tools.nvim: ...s/yuanhe/.config/nvim/lua/archvim/config/cmake-tools.lua:1: loop or previous error loading module 'cmake-tools'
packer.nvim: Error running config for neogit: ...m/site/pack/packer/start/neogit/lua/neogit/lib/state.lua:19: attempt to index a nil value
```

**Comment by archibate** [comment]
这个错误应该不影响使用，nvim螚正常打开即可，另外，我又更新了一下安装脚本，现在brew不会sudo了，你可以试试看











无法顺畅的大口呼吸，是活着的最好证明

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月18日(周三) 晚上7:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [archibate/vimrc] 【macOS】安装过程遇到问题 (Issue #35)




 
补充：
 以上情况2种没有等待输入的问题可能是brew没有正确安装依赖， 以普通权限运行bash ~/.config/nvim/install_deps.sh后再运行安装脚本就好了， 不过还是会有错误报出， 错误与前述日志一致， 即：
 处理 /Users/yuanhe/.config/nvim/lua/archvim/predownload/Civitasv/cmake-tools.nvim/plugin/cmake-tools.lua 时发生错误: E5113: Error while calling lua chunk: ...ownload/Civitasv/cmake-tools.nvim/plugin/cmake-tools.lua:4: loop or previous error loading module 'cmake-tools' stack traceback: [C]: in function 'require' ...ownload/Civitasv/cmake-tools.nvim/plugin/cmake-tools.lua:4: in main chunk 处理 command line 时发生错误: packer.nvim: Error running config for cmake-tools.nvim: ...s/yuanhe/.config/nvim/lua/archvim/config/cmake-tools.lua:1: loop or previous error loading module 'cmake-tools' packer.nvim: Error running config for neogit: ...m/site/pack/packer/start/neogit/lua/neogit/lib/state.lua:19: attempt to index a nil value

**Comment by hyv5** [comment]
感谢修改

经过测试:
1. 安装脚本中brew处理正常
2. nvim可以正常打开
